---
title: "CTSBS Age-Mixing"
author: "Roxanne Beauclair"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output: html_document
---

```{r setup, include = FALSE}
# ===================
# Relative file paths
# ===================
wd <- "/Users/roxannebeauclair/Documents/Analytical Projects/PhD/CTSBS Age Mixing/Analysis"
cdata <- paste0(wd, "/Data/Cleaned")

imputedata <- paste0(cdata, "/ctsbs_impute_data.rda")

fxn <- paste0(wd, "/Scripts/00-Functions.R")

# ====================
# Loading dependencies
# ====================
source(fxn)

# magrittr: for use of %>% operator
# tidyverse: for data management functions
# mice: for MI


InstallLoad("magrittr", "tidyverse", "mice",
            "CALIBERrfimpute", "nlme", "modelr",
            "splines", "mgcv", "broom")

# =============
# Load datasets
# =============
load(imputedata)

# ====================
# Set specific global options
# ====================

# Set theme for plots
theme <- theme(axis.title.x = element_text(face = "bold", size = 10),
             axis.text.x  = element_text(angle = 0, face = "bold",
                                         colour = "black", size = 8),
             axis.title.y = element_text(face = "bold", size = 10),
             axis.text.y = element_text(angle = 0, 
                                        face = "bold", 
                                        colour = "black", 
                                        hjust = 0.5,
                                        size = 8),
             plot.title = element_text(lineheight = .8, face = "bold"),
             panel.grid.major = element_line(colour = 'grey82'),
             panel.grid.minor = element_line(colour = NA),
             panel.background = element_rect(fill = 'white'),
             strip.background = element_rect(fill = 'white'),
             strip.text = element_text(size = 8, face = "bold"),
             legend.title = element_text(colour = "black", size = 9, face = "bold"),
             legend.text = element_text(size = 8, face = "bold"),
             plot.margin = unit(c(1.5,1,1,1), "lines"))


# Initialize table counter
options(show.signif.stars = F)
```


```{r ampfig setup, include = FALSE}

imp <- max(as.integer(dfimp$.imp)) - 1
set.seed(47621)
n <- sample(1:imp, 1)

# Smaller datasets
df <- dfimp %>%
  filter(.imp == n)%>%
  mutate(agemean = age - round(mean(age), 2),
         age2sd = age - round(2 * sd(age), 2)) %>%
  select(id, age, agemean, age2sd, agep, sex,
         missage, missagep, hiv) 

men <- df %>%
  filter(sex == "Male")

women <- df %>%
  filter(sex == "Female")


# Now fit separate models for men and women
modelm1 <- lme(agep ~ agemean, 
           data = men, 
           random = ~1 | id,  
           #weights = varPower(value = 0.5, form = ~agemean + 1),
           method = "REML")

modelw1 <- lme(agep ~ agemean, 
           data = women, 
           random = ~1 | id,  
           #weights = varPower(value = 0.5, form = ~agemean + 1),
           method = "REML")

modelm2 <- gamm(agep ~ s(agemean), 
           data = men, 
           random = list(id = ~1))

modelw2 <- gamm(agep ~ s(agemean), 
           data = women, 
           random = list(id = ~1))


# Add the predicted values to the dataset
menadd <- men %>%
  mutate(pred.1 = predict(modelm1, newdata = ., level = 0),
         pred.2 = predict(modelm2$gam, newdata = .),
         resid.2 = residuals(modelm2$gam)) %>%
  add_residuals(modelm1, var = "resid.1")

womenadd <- women %>%
  mutate(pred.1 = predict(modelw1, newdata = ., level = 0),
         pred.2 = predict(modelw2$gam, newdata = .),
         resid.2 = residuals(modelw2$gam))%>%
  add_residuals(modelw1, var = "resid.1") 

#Combine both datasets again
comb <- bind_rows(menadd, womenadd) %>%
  gather(key, value, -id:-hiv) %>%
  separate(key, into = c("type", "model"), sep = "\\.")
  
```

```{r ampfig, echo = FALSE}

ampfig <- comb %>%
  filter(type == "pred") %>%
  ggplot(aes(x = age, y = value)) +
  geom_point(aes(x = age, 
                 y = agep, 
                 color = missagep), 
             position = position_jitter(width = 0.75, height = 0.75),
             size = 1) +
  geom_abline(size = 1, 
              aes(intercept = 0, slope = 1, linetype = "Same age"), 
              show.legend = FALSE) +
  geom_line(aes(linetype = "Population mean"), 
            size = 1) +
  facet_wrap(model ~ sex) + 
  scale_y_continuous(name = "Partner's ages") +
  scale_color_manual('Imputation Status', values = c('grey70', 'grey42')) +
  scale_linetype_manual('Lines', values = c("Population mean" = 1, 'Same age' = 2)) +
  xlab("Participant's age (centered on mean age)") +
  guides(linetype = guide_legend(keywidth = 2, keyheight = 1)) +
  theme

ampfig

```

```{r ampres, echo = FALSE}
ampresfig1 <- comb %>%
  filter(type == "resid") %>%
  ggplot(aes(value)) +
  geom_freqpoly(binwidth = 0.5) +
  facet_grid(model ~ sex) +
  theme

ampresfig1

ampresfig2 <- comb %>%
  filter(type == "resid") %>%
  ggplot(aes(x = age, y = value)) +
  geom_point() +
  geom_smooth(method = "loess") +
  geom_ref_line(h = 0) +
  facet_grid(model ~ sex) + 
  theme

ampresfig2

```

```{r amp_all, include = FALSE}

byimpsex <- dfimp %>% 
  filter(.imp != 0) %>%
  group_by(.imp, sex) %>%
  mutate(agemean = age - round(mean(age), 2),
         agegroup = cut(age, 
                        breaks = c(14, 24, 34, 44, 54, 70),
                        labels = c("15-24", "25-34", "35-44", "45-54", "55-70")),
         agepgroup = cut(agep, 
                        breaks = c(10, 24, 34, 44, 54, 100),
                        labels = c("<=24", "25-34", "35-44", "45-54", ">=55")))%>%
  nest()

tidysummary <- byimpsex %>%
  mutate(model = map(data, ampmodel),
         modelsum = map(model, ~tidy(.x, effects = "fixed")),
         bvar = map(model, bvar),
         wvar = map(model, wvar))
 
modslopeint <- tidysummary %>%
  unnest(modelsum, .drop = TRUE)

modwvar <- tidysummary %>%
  unnest(wvar, .drop = TRUE)

modbvar <- tidysummary %>%
  unnest(bvar, .drop = TRUE)

```

```{r amp_model_plots, echo = FALSE}
slopeplot <- modslopeint %>%
  filter(term == "agemean") %>%
  ggplot(aes(x = .imp, y = estimate)) +
  geom_point() +
  geom_pointrange(aes(ymax = estimate + 2 * std.error,
                      ymin = estimate - 2 * std.error)) +
  facet_grid(sex ~ .) +
  coord_flip() +
  xlab("Imputation") +
  ylab("Slope of regression line") +
  theme

slopeplot



interplot <- modslopeint %>%
  filter(term == "(Intercept)") %>%
  ggplot(aes(.imp, estimate)) +
  geom_point() +
  geom_pointrange(aes(ymax = estimate + 2 * std.error,
                      ymin = estimate - 2 * std.error)) +
  facet_grid(sex ~ .) +
  coord_flip() +
  xlab("Imputation") +
  ylab("Partner age for average age") +
  theme

interplot

wvarplot <- modwvar %>%
  ggplot(aes(.imp, wsd)) +
  geom_point() +
  geom_pointrange(aes(ymax = uprwsd,
                      ymin = lwrwsd)) +
  facet_grid(sex ~ .) +
  coord_flip() +
  xlab("Imputation") +
  ylab("Within-Subject SD") +
  theme

wvarplot

bvarplot <- modbvar %>%
  ggplot(aes(.imp, bsd)) +
  geom_point() +
  geom_pointrange(aes(ymax = uprbsd,
                      ymin = lwrbsd)) +
  facet_grid(sex ~ .) +
  coord_flip() +
  xlab("Imputation") +
  ylab("Between-Subject SD") +
  theme

bvarplot
```

```{r ageprop_hiv, echo = FALSE}
hivbyage <- byimpsex %>%
  unnest() %>%
  filter(.imp == n & hiv == "Positive") %>%
  group_by(sex, agepgroup) %>%
  summarise(n = n()) %>%
  mutate(prop = round((n / sum(n)) * 100, 2))
  
hivplot <- hivbyage %>%
  ggplot(aes(x = agepgroup, y = prop, fill = sex)) +
  geom_bar(stat = "identity",
           position = position_dodge()) +
  xlab("Age group of partner") +
  ylab("Proportion of relationships") +
  scale_fill_brewer(palette = "Dark2") +
  theme

hivplot
  
```

```{r hivampfig setup, include = FALSE}

# Smaller datasets
men <- df %>%
  filter(sex == "Male" & hiv == "Positive")

women <- df %>%
  filter(sex == "Female" & hiv == "Positive")


# Now fit separate models for men and women
modelmhiv <- lme(agep ~ age, 
           data = men, 
           random = ~1 | id,  
           method = "REML")

modelwhiv <- lme(agep ~ age, 
           data = women, 
           random = ~1 | id,
           method = "REML")



# Add the predicted values to the dataset
menadd <- men %>%
  mutate(pred = predict(modelmhiv, newdata = ., level = 0))

womenadd <- women %>%
  mutate(pred = predict(modelwhiv, newdata = ., level = 0)) 

#Combine both datasets again
comb <- bind_rows(menadd, womenadd) 
  
```

```{r hivampfig, echo = FALSE}

hivampfig <- comb %>%
  ggplot(aes(x = age, y = pred)) +
  geom_point(aes(x = age, 
                 y = agep, 
                 color = missagep), 
             position = position_jitter(width = 0.75, height = 0.75),
             size = 1) +
  geom_abline(size = 1, 
              aes(intercept = 0, slope = 1, linetype = "Same age"), 
              show.legend = FALSE) +
  geom_line(aes(linetype = "Population mean"), 
            size = 1) +
  facet_wrap(~ sex) + 
  scale_y_continuous(name = "Partner's ages") +
  scale_color_manual('Imputation Status', values = c('grey70', 'grey42')) +
  scale_linetype_manual('Lines', values = c("Population mean" = 1, 'Same age' = 2)) +
  xlab("Participant's age") +
  guides(linetype = guide_legend(keywidth = 2, keyheight = 1)) +
  theme

hivampfig

```


```{r close, include = FALSE}
# ====================================================
# Detach libraries and remove objects from environment
# ====================================================
Vectorize(detach)(name = paste0("package:", c("tidyverse",
                                              "CALIBERrfimpute",
                                              "mice")), 
                  unload = TRUE, 
                  character.only = TRUE)

rm(list=ls())

```

