---
title: "Missingness exploration"
author: "Roxanne Beauclair"
date: '`r format(Sys.Date(), "%d %B %Y")`'
output: html_document
---

```{r setup, include = FALSE}
# ===================
# Relative file paths
# ===================
wd <- "/Users/roxannebeauclair/Documents/Analytical Projects/PhD/CTSBS Age Mixing/Analysis"

cdata <- paste0(wd, "/Data/Cleaned")

excludedata <- paste0(cdata, "/ctsbs_excluded_data.rda")

fxn <- paste0(wd, "/Scripts/00-Functions.R")

# ====================
# Loading dependencies
# ====================
source(fxn)

# magrittr: for use of %>% operator
# tidyverse: for data management functions


InstallLoad("magrittr", "tidyverse")

# =============
# Load datasets
# =============
load(excludedata)


# ===============
# Global settings
# ===============

theme <- theme(axis.title.x = element_text(face = "bold", size = 10),
             axis.text.x  = element_text(angle = 0, face = "bold",
                                         colour = "black", size = 8),
             axis.title.y = element_text(face = "bold", size = 10),
             axis.text.y = element_text(angle = 0, 
                                        face = "bold", 
                                        colour = "black", 
                                        hjust = 0.5,
                                        size = 8),
             plot.title = element_text(lineheight = .8, face = "bold"),
             panel.grid.major = element_line(colour = 'grey82'),
             panel.grid.minor = element_line(colour = NA),
             panel.background = element_rect(fill = 'white'),
             strip.background = element_rect(fill = 'white'),
             strip.text = element_text(size = 8, face = "bold"),
             legend.title = element_text(colour = "black", size = 9, face = "bold"),
             legend.text = element_text(size = 8, face = "bold"),
             plot.margin = unit(c(1.5,1,1,1), "lines"))

# Initialize table counter
options(show.signif.stars = F)


```

```{r variation, echo = FALSE, warning = FALSE, message = FALSE}

df %>% ggplot() +
  geom_bar(aes(x = relcf)) + 
  theme

df %>% ggplot() +
  geom_bar(aes(x = ongoing)) + 
  theme

df %>% ggplot() +
  geom_histogram(aes(x = relsf)) + 
  theme

summary(df$relsf)

df %>% ggplot() + 
  geom_bar(aes(x = relconcur)) +
  theme

df %>% ggplot() + 
  geom_bar(aes(x = hiv)) + 
  theme

df %>% ggplot() +
  geom_histogram(aes(x = relcount)) +
  theme

summary(df$relcount)

df %>% ggplot() +
  geom_histogram(aes(x = reldurweeks)) +
  theme

summary(df$reldurweeks)

df %>% ggplot() +
  geom_histogram(aes(x = agedif)) + 
  theme

summary(df$agedif)
agedifoutly <- filter(df, agedif <= -40 |
                        agedif >= 40)

agedifoutly

df %>% ggplot() +
  geom_bar(aes(x = pt)) +
  theme

df %>% ggplot() +
  geom_histogram(aes(x = age)) +
  theme

summary(df$age)

df %>% ggplot() +
  geom_bar(aes(x = race)) + 
  theme

df %>% ggplot() +
  geom_bar(aes(x = sex)) +
  theme

df %>% ggplot() +
  geom_bar(aes(x = job)) +
  theme

df %>% ggplot() +
  geom_bar(aes(x = grade)) +
  theme

```

```{r covariation, echo = FALSE, warning = FALSE, message = FALSE}
# Sex frequency
df %>% ggplot(aes(x = job, y = relsf)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = grade, y = relsf)) +
  geom_boxplot() +
  coord_flip() +
  theme

df %>% ggplot(aes(x = sex, y = relsf)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = race, y = relsf)) +
  geom_boxplot() +
  theme

df %>% ggplot() +
  geom_boxplot(aes(x = reorder(pt, relsf, FUN = median),
                   y = relsf)) +
  theme

df %>% ggplot(aes(x = hiv, y = relsf)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relconcur, y = relsf)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = ongoing, y = relsf)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relcf, y = relsf)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = reldurweeks, y = relsf)) +
  geom_point(alpha = 0.20) +
  theme

df %>% ggplot(aes(x = agedif, y = relsf)) +
  geom_hex() +
  theme

df %>% ggplot(aes(x = relcount, y = relsf)) +
  geom_boxplot(aes(group = cut_width(relcount, 1))) +
  theme

df %>% ggplot(aes(x = age, y = relsf)) +
  geom_hex() +
  theme

# Relationship duration
df %>% ggplot(aes(x = job, y = reldurweeks)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = grade, y = reldurweeks)) +
  geom_boxplot() +
  coord_flip() +
  theme

df %>% ggplot(aes(x = sex, y = reldurweeks)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = race, y = reldurweeks)) +
  geom_boxplot() +
  theme

df %>% ggplot() +
  geom_boxplot(aes(x = reorder(pt, reldurweeks, FUN = median),
                   y = reldurweeks)) +
  theme

df %>% ggplot(aes(x = hiv, y = reldurweeks)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relconcur, y = reldurweeks)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = ongoing, y = reldurweeks)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relcf, y = reldurweeks)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = agedif, y = reldurweeks)) +
  geom_hex() +
  theme

df %>% ggplot(aes(x = relcount, y = reldurweeks)) +
  geom_boxplot(aes(group = cut_width(relcount, 1))) +
  theme

df %>% ggplot(aes(x = age, y = reldurweeks)) +
  geom_hex() +
  theme

# Age difference
df %>% ggplot(aes(x = job, y = agedif)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = grade, y = agedif)) +
  geom_boxplot() +
  coord_flip() +
  theme

df %>% ggplot(aes(x = sex, y = agedif)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = race, y = agedif)) +
  geom_boxplot() +
  theme

df %>% ggplot() +
  geom_boxplot(aes(x = reorder(pt, agedif, FUN = median),
                   y = agedif)) +
  theme

df %>% ggplot(aes(x = hiv, y = agedif)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relconcur, y = agedif)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = ongoing, y = agedif)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relcf, y = agedif)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relcount, y = agedif)) +
  geom_boxplot(aes(group = cut_width(relcount, 1))) +
  theme

df %>% ggplot(aes(x = age, y = agedif)) +
  geom_hex() +
  theme

# Relationship count
df %>% ggplot(aes(x = job, y = relcount)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = grade, y = relcount)) +
  geom_boxplot() +
  coord_flip() +
  theme

df %>% ggplot(aes(x = sex, y = relcount)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = race, y = relcount)) +
  geom_boxplot() +
  theme

df %>% ggplot() +
  geom_boxplot(aes(x = reorder(pt, relcount, FUN = median),
                   y = relcount)) +
  theme

df %>% ggplot(aes(x = hiv, y = relcount)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relconcur, y = relcount)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = ongoing, y = relcount)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relcf, y = relcount)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = age, y = relcount)) +
  geom_hex() +
  theme

# Age
df %>% ggplot(aes(x = job, y = age)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = grade, y = age)) +
  geom_boxplot() +
  coord_flip() +
  theme

df %>% ggplot(aes(x = sex, y = age)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = race, y = age)) +
  geom_boxplot() +
  theme

df %>% ggplot() +
  geom_boxplot(aes(x = reorder(pt, age, FUN = median),
                   y = age)) +
  theme

df %>% ggplot(aes(x = hiv, y = age)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relconcur, y = age)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = ongoing, y = age)) +
  geom_boxplot() +
  theme

df %>% ggplot(aes(x = relcf, y = age)) +
  geom_boxplot() +
  theme

# Concurrency
df %>% ggplot() +
  geom_count(aes(x = job, y = relconcur)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = grade, y = relconcur)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = sex, y = relconcur)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = race, y = relconcur)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = pt, y = relconcur)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = hiv, y = relconcur)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = ongoing, y = relconcur)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = relcf, y = relconcur)) +
  theme

# Condoms
df %>% ggplot() +
  geom_count(aes(x = job, y = relcf)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = grade, y = relcf)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = sex, y = relcf)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = race, y = relcf)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = pt, y = relcf)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = hiv, y = relcf)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = ongoing, y = relcf)) +
  theme

# HIV
df %>% ggplot() +
  geom_count(aes(x = job, y = hiv)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = grade, y = hiv)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = sex, y = hiv)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = race, y = hiv)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = pt, y = hiv)) +
  theme

df %>% ggplot() +
  geom_count(aes(x = ongoing, y = hiv)) +
  theme

```


```{r, include = FALSE}
# ====================================================
# Detach libraries and remove objects from environment
# ====================================================
Vectorize(detach)(name = paste0("package:", c("tidyverse")), 
                  unload = TRUE, 
                  character.only = TRUE)

rm(list=ls())

```

