---
title: "Results"
output: html_document
---
### **KEY RESULTS TO DISCUSS**

1. Not much difference between the slopes in each sub-population: Average partner age increases with each year increase in participant age between: `r round(slopeintci$lwr[8], 2)` and `r round(slopeintci$upr[5], 2)`

2. When HIV negative men and women are 15 years old, the average difference between the population average partner age is approximately 5 years, with men having female partners who are `r round(slopeintci$mean[3])` years old on average and women `r round(slopeintci$mean[1])` years old on average. I think it is important to note here that young men also have older partners, and in Figure 1 we see that 20% of 15-24 year old women are HIV positive, compared to roughly 10% of men. Also the HIV positive 15 year olds seem to choose even older partners (mean: `r round(slopeintci$mean[4])`) although the distribution is more widespread.

3. HIV positive women have larger wsd's AND bsd's than HIV negative women. Women with HIV are also expected to have nearly 3 times larger bridgewidths than HIV negative women. Are women actually driving HIV transmission?

4. What do we make of the bimodal distribution of bsd's in HIV positive men? Just an artifact of uncertainty in participant age for their imputations? Of missing partner partner ages 65% were from men (not depicted here, but will be a supplementary web appendix)

5. Expected bridgewidths probably increase with age in both men and women, although in women there is a slight hint that younger and older women might have higher BW's than middle-aged women.

### **RESULTS**

We randomly selected one of the 50 imputed data sets from which to calculate the HIV prevalence in this Cape Town population (Figure 1). In most age groups, women had had a higher HIV prevalence than men. For women aged 15-24, their HIV prevalence was nearly twice that of the men in that same age group (`r round(hivprev$prop[20] * 100, 1)`% in women vs. `r round(hivprev$prop[2] * 100, 1)`% in men). This disparity was even more striking in 25-29-year-olds, with `r round(hivprev$prop[22] * 100, 1)`% of women infected and only `r round(hivprev$prop[4] * 100, 1)`% of men infected. HIV prevalence peaked in women 30-34 years old (`r round(hivprev$prop[24] * 100, 1)`%) and in men who were 60 years or older (`r round(hivprev$prop[18] * 100, 1)`%).

Figure 2 shows the distribution of model B-coefficients, which represents how fast the age differences grew as participants aged. For all sub-populations the average partner ages increased with each year increase in participant age, with the smallest model B-coefficient being `r round(slopeintci$lwr[8], 2)` in HPM and the largest being `r round(slopeintci$upr[5], 2)` in HPW (Figure 2). Most of the distributions seem to overlap to a great extent and in Table 1, we see there were not large differences in B-coefficients between the groups, all differences overlapped with zero. Also in Table 1 we see that for the HNM and HNW the model intercept difference was approximately `r round(intdifci$meangendifneg)` years (95% CI: `r intdifci$lwrgendifneg` - `r intdifci$uprgendifneg`), with 15-year-old men and women in those groups having partners who were `r round(slopeintci$mean[3])` (95% CI: `r round(slopeintci$lwr[3])` - `r round(slopeintci$upr[3])`) and `r round(slopeintci$mean[1])`-years-old (95% CI: `r round(slopeintci$lwr[1])` - `r round(slopeintci$upr[1])`) on average, respectively (Figure 3). 

HNM had the largest between-subject standard deviation (BSSD: `r round(bsdci$mean[3], 2)`; 95% CI: `r round(bsdci$lwr[3], 2)` - `r round(bsdci$upr[3], 2)`) while HPW had the lowest (BSSD: `r round(bsdci$mean[2], 2)`; 95% CI: `r round(bsdci$lwr[2], 2)` - `r round(bsdci$upr[2], 2)`) (Figure 4). Table 1 shows that there was a relatively large and significant difference between the BSSD in HPW and HNW (`r bvardifci$meanhivdiffemale`, 95% CI: `r bvardifci$lwrhivdiffemale` - `r bvardifci$uprhivdiffemale`). The distribution of BSSD's in HPM appears to be bi-modal, but this is most likely due to uncertainty in the imputations for partner age in this sub-population. Figure 5 shows that the within-subject standard deviation (WSSD) was the largest for HPW (WSSD: `r round(wsdci$mean[2], 2)`; 95% CI: `r round(wsdci$lwr[2], 2)` - `r round(wsdci$upr[2], 2)`) and the smallest for HNW (WSSD: `r round(wsdci$mean[1], 2)`; 95% CI: `r round(wsdci$lwr[1], 2)` - `r round(wsdci$upr[1], 2)`), with the difference between the two groups being `r round(wvardifci$meanhivdiffemale, 2)` (95% CI: `r round(wvardifci$lwrhivdiffemale, 2)` - `r round(wvardifci$uprhivdiffemale, 2)`) (Table 1). For the other group comparisons, the BSSD and WSSD appear to be similar and their distributions have a large degree of overlap.

In the complete study population `r parts_many_partner` participants reported having more than one relationship in the previous year (`r round(parts_many_partner / parts_left * 100, 2)`%). Figure 6 shows the distribution of bridge widths — range in partner ages — by sub-population. In all sub-populations the distributions are right-skewed, with the bulk of the density in all imputations being less than 20 years. In both HIV positive groups, there appears to be fatter tails, implying that those with HIV may have larger bridge widths. Although, there is more uncertainty in the imputations of HPM. The results of our individual-level negative-binomial models are presented in Figures 7 and 8. Across all imputations, having an HIV-positive diagnosis increased the expected bridge width of women by almost `r round(womenEBWR)` times that of those who were HIV-negative (95% CI: `r womenEBWRlwr` - `r womenEBWRupr`). Among men there also seems to be an increased expectation of larger bridge widths in HIV positive participants compared to HIV negative participants, although when all of the estimates are pooled for all imputed data sets, the evidence does not appear to be as strong (EBWR: `r menEBWR`; 95% CI: `r menEBWRlwr` - `r menEBWRupr`). 

Finally, in both men and women there appears to be a relationship between increasing participant age and larger expected ranges between partner ages, although the uncertainty in the imputations is reflected by there being large variation in expected bridge widths at older ages. For women, in most of the imputed data sets, the relationship between age and expected bridge widths is non-linear, with the youngest and oldest participants having larger expected bridge widths, and those between 25 and 45 years old having smaller bridge widths. 