---
title: "Supplementary CC analysis"
author: "Roxanne Beauclair"
date: "2/6/2018"
output: html_document
---

```{r setup, include = FALSE}
# ===================
# Relative file paths
# ===================
wd <- "/Users/roxannebeauclair/Documents/Analytical Projects/PhD/CTSbS Age Mixing/Analysis"
cdata <- paste0(wd, "/Data/Cleaned")

excludedata <- paste0(cdata, "/ctsbs_excluded_data.rda")
imputedatapart <- paste0(cdata, "/ctsbs_impute_data_part.rda")



fxn <- paste0(wd, "/Scripts/00-Functions.R")

# ====================
# Loading dependencies
# ====================
source(fxn)

# magrittr: for use of %>% operator
# tidyverse: for data management functions
# mice: for MI


InstallLoad("magrittr", "MASS", "tidyr", 
            "dplyr", "purrr", "tibble",
            "mice","nlme", "lme4", "modelr",
            "mgcv", "gamm4", "broom", "splines", 
            "forcats", "Gmisc", "htmlTable")

# Need development version
library(ggplot2)

# =============
# Load datasets
# =============
load(excludedata)
load(imputedatapart)


# ====================
# Set specific global options
# ====================

# Set theme for plots
theme <- theme(axis.title.x = element_text(face = "bold", size = 10),
             axis.text.x  = element_text(angle = 0, face = "bold",
                                         colour = "black", size = 8),
             axis.title.y = element_text(face = "bold", size = 10),
             axis.text.y = element_text(angle = 0, 
                                        face = "bold", 
                                        colour = "black", 
                                        hjust = 0.5,
                                        size = 8),
             plot.title = element_text(lineheight = .8, face = "bold"),
             panel.grid.major = element_line(colour = 'grey82'),
             panel.grid.minor = element_line(colour = NA),
             panel.background = element_rect(fill = 'white'),
             strip.background = element_rect(fill = 'white'),
             strip.text = element_text(size = 8, face = "bold"),
             legend.title = element_text(colour = "black", size = 9, face = "bold"),
             legend.text = element_text(size = 8, face = "bold"),
             plot.margin = unit(c(1.5,1,1,1), "lines"))


# Initialize table counter
options(show.signif.stars = F)

```

```{r rel_chars_setup, include = FALSE, warning = FALSE, message = FALSE}

# Subset of variables that were also used for imputation
smalldf <- df %>%
  select(id, age, sex,  
         job, grade, hiv, relid, 
         relseq, relcount, pt, slept, 
         agep, live, otherpart, ongoing, 
         relconcur, relsf, relcf, reldurweeks,
         easy, private, truth, start) %>%
  mutate(agecat = fct_explicit_na(cut(age,
                                      breaks = c(0, 24, 34, 44, 100),
                                      labels = c("15-24", "25-34", "35-44", "45-70")),
                                  na_level = "Missing"),
         age0 = age - 15,
         hivstat = fct_explicit_na(hiv, na_level = "Missing"),
         easy = fct_explicit_na(easy, na_level = "Missing"),
         job = fct_explicit_na(job, na_level = "Missing"),
         grade = fct_explicit_na(grade, na_level = "Missing"),
         agepcat = fct_explicit_na(cut(agep,
                                       breaks = c(0, 24, 34, 44, 100),
                                       labels = c("<= 24", "25-34", "35-44", ">= 45")),
                                   na_level = "Missing"),
         relsfcat = fct_explicit_na(cut(relsf,
                                        breaks = c(-1, 0, 1, 2, 3, 4, 17),
                                        labels = c("None", "1 time/week", 
                                                   "2 times/week", "3 times/week", 
                                                   "4 times/week", ">= 5 times/week")),
                                    na_level = "Missing"),
         cf = fct_explicit_na(fct_collapse(relcf,
                                           "Never/inconsistent" = c("Never", "Inconsistent")),
                              na_level = "Missing"),
         mcp = fct_explicit_na(relconcur, na_level = "Missing"),
         pt = fct_collapse(pt,
                           "Main" = c("MP", "OMP"),
                           "Casual" = "CP"),
         ongoing = fct_explicit_na(ongoing, na_level = "Missing"))

tab1 <- list()

tab1[["Age"]] <- GetT1Stat(smalldf$agecat, smalldf$sex)
tab1[["Employed"]] <- GetT1Stat(smalldf$job, smalldf$sex)
tab1[["Highest grade completed"]] <- GetT1Stat(smalldf$grade, smalldf$sex)
tab1[["HIV status"]] <- GetT1Stat(smalldf$hivstat, smalldf$sex)
tab1[["ACASI survey difficulty"]] <- GetT1Stat(smalldf$easy, smalldf$sex)
tab1[["Number relationships in past year"]] <- GetT1Stat(smalldf$relcount, smalldf$sex)
tab1[["Partner age"]] <- GetT1Stat(smalldf$agepcat, smalldf$sex)
tab1[["Partner type"]] <- GetT1Stat(smalldf$pt, smalldf$sex)
tab1[["Relationship was concurrent"]] <- GetT1Stat(smalldf$mcp, smalldf$sex)
tab1[["Sex frequency"]] <- GetT1Stat(smalldf$relsfcat, smalldf$sex)
tab1[["Relationship ongoing"]] <- GetT1Stat(smalldf$ongoing, smalldf$sex)
tab1[["Condom frequency"]] <- GetT1Stat(smalldf$cf, smalldf$sex)

```

```{r rel_chars_tab, echo = FALSE, warning = FALSE, message = FALSE}
mergeDesc(tab1) %>%
  htmlTable(caption = "<b>Table 1. Relationship characteristics by sex using the original dataset<b/>",
            tfoot = "All continuous values are reported with median and interquartile range, Med (IQR), while categories are reported in percentages, n (%). There were 27 relationships that belonged to participants with missing gender status, and thus were excluded from this table.",
            rowlabel = "Variables",
            cgroup = "Sex",
            n.cgroup = ncol(tab1[[1]]),
            ctable = TRUE,
            padding.rgroup = "&nbsp; &nbsp; &nbsp;")


```

```{r hiv_prev, echo = FALSE, message = FALSE, warning = FALSE}
# Create row for HIV positive men aged 15-24
filler <- tibble(sex = "Male", 
                 agegroup = "15-24", 
                 hiv = "Positive", 
                 n = 0, 
                 total = 0, 
                 prop = 0, 
                 ll = 0, 
                 ul = 0)

hivprev <- smalldf %>%
  mutate(agegroup = cut(age,
                        breaks = c(0, 24, 29, 34, 
                                   39, 44, 49, 54, 59,
                                   70),
                        labels = c("15-24", "25-29", 
                                   "30-34", "35-39", "40-44", 
                                   "45-49", "50-54", "55-59", 
                                   "60+"))) %>%
  group_by(sex, agegroup, hiv) %>%
  summarise(n = n()) %>%
  mutate(total = sum(n),
         prop = n / total) %>%
  ungroup() %>%
  group_by(sex, agegroup, hiv, n, total) %>%          # The binom.test() function is not vectorized,
  mutate(ll = binom.test(n, total)$conf.int[1],       # and thus, we need to make sure each row is   
         ul = binom.test(n, total)$conf.int[2]) %>% 
  filter(hiv == "Positive",
         !is.na(sex),
         !is.na(agegroup)) %>%
  bind_rows(filler)
  

hivprevplot <- hivprev %>%
  ggplot(aes(x = agegroup, y = prop, fill = sex)) +
  geom_bar(stat = "identity",
           position = position_dodge(0.9)) +
  geom_errorbar(aes(ymax = ul, ymin = ll),
                position = position_dodge(0.9),
                width = 0.10) +
  xlab("Age group") +
  ylab("Proportion") +
  scale_fill_hue(name = "Gender") +
  theme

hivprevplot

```
<br>
<br>


```{r ampmodel, echo = FALSE, message = FALSE, warning = FALSE}
# Create a grouped dataset for different population strata
# Remove missing observations for sex, hiv, age, and page
strata <- smalldf %>%
  select(id, sex, hiv, agep, age0) %>%
  group_by(sex, hiv) %>%
  na.omit()

strata

# Proportions of CC 
tidysum <- strata %>%
  count(sex, hiv) %>%
  ungroup() %>%
  mutate(total = sum(n), 
         prop = round((n / total) * 100, 2))
tidysum

# Age-mixing models applied to four strata of CC
tidysumamp <- strata %>%
  nest() %>%
  mutate(model = map(data, ampmodel),
         modelsum = map(model, ~tidy(.x, 
                                     effects = "fixed", 
                                     conf.int = TRUE)), 
         bvar = map(model, bvar), 
         wvar = map(model, wvar))

# Extract slopes and intercepts
modslopeint <- tidysumamp %>%
  unnest(modelsum, .drop = TRUE) 

modslopeint

# Extract bvars
modbvar <- tidysumamp%>%
  unnest(bvar, .drop = TRUE)

modbvar

# Extract wvars
modwvar <- tidysumamp %>%
  unnest(wvar, .drop = TRUE)

modwvar

```


```{r amp_model_tab_setup, include = FALSE}

# Matrix for  model results
mx <- matrix(ncol = 4, nrow = 4)
rownames(mx) <- c("HNW", "HPW", "HNM", "HPM")
colnames(mx) <- c("B-coefficient", "Intercept", "BSSD", "WSSD")


mx[1, 1] <- paste0(round(modslopeint$estimate[6], 2), " (", round(modslopeint$conf.low[6], 2), " — ", round(modslopeint$conf.high[6], 2), ")")
mx[2, 1] <- paste0(round(modslopeint$estimate[2], 2), " (", round(modslopeint$conf.low[2], 2), " — ", round(modslopeint$conf.high[2], 2), ")")
mx[3, 1] <- paste0(round(modslopeint$estimate[4], 2), " (", round(modslopeint$conf.low[4], 2), " — ", round(modslopeint$conf.high[4], 2), ")")
mx[4, 1] <- paste0(round(modslopeint$estimate[8], 2), " (", round(modslopeint$conf.low[8], 2), " — ", round(modslopeint$conf.high[8], 2), ")")

mx[1, 2] <- paste0(round(modslopeint$estimate[5], 2), " (", round(modslopeint$conf.low[5], 2), " — ", round(modslopeint$conf.high[5], 2), ")")
mx[2, 2] <- paste0(round(modslopeint$estimate[1], 2), " (", round(modslopeint$conf.low[1], 2), " — ", round(modslopeint$conf.high[1], 2), ")")
mx[3, 2] <- paste0(round(modslopeint$estimate[3], 2), " (", round(modslopeint$conf.low[3], 2), " — ", round(modslopeint$conf.high[3], 2), ")")
mx[4, 2] <- paste0(round(modslopeint$estimate[7], 2), " (", round(modslopeint$conf.low[7], 2), " — ", round(modslopeint$conf.high[7], 2), ")")

mx[1, 3] <- paste0(round(modbvar$bsd[3], 2), " (", round(modbvar$lwrbsd[3], 2), " — ", round(modbvar$uprbsd[3], 2), ")")
mx[2, 3] <- paste0(round(modbvar$bsd[1], 2), " (", round(modbvar$lwrbsd[1], 2), " — ", round(modbvar$uprbsd[1], 2), ")")
mx[3, 3] <- paste0(round(modbvar$bsd[2], 2), " (", round(modbvar$lwrbsd[2], 2), " — ", round(modbvar$uprbsd[2], 2), ")")
mx[4, 3] <- paste0(round(modbvar$bsd[4], 2), " (", round(modbvar$lwrbsd[4], 2), " — ", round(modbvar$uprbsd[4], 2), ")")

mx[1, 4] <- paste0(round(modwvar$wsd[3], 2), " (", round(modwvar$lwrwsd[3], 2), " — ", round(modwvar$uprwsd[3], 2), ")")
mx[2, 4] <- paste0(round(modwvar$wsd[1], 2), " (", round(modwvar$lwrwsd[1], 2), " — ", round(modwvar$uprwsd[1], 2), ")")
mx[3, 4] <- paste0(round(modwvar$wsd[2], 2), " (", round(modwvar$lwrwsd[2], 2), " — ", round(modwvar$uprwsd[2], 2), ")")
mx[4, 4] <- paste0(round(modwvar$wsd[4], 2), " (", round(modwvar$lwrwsd[4], 2), " — ", round(modwvar$uprwsd[4], 2), ")")

```

<br>
<br>

```{r amp_model_tab, echo = FALSE, fig.width = 10}


mx %>%
  htmlTable(caption = "<b>Table 2. Linear mixed effects model age-mixing pattern features for different population strata. This analysis was done with complete cases.</b>",
            tfoot = txtMergeLines("HNM, HIV Negative Men", 
                                 "HNW, HIV Negative Women",
                                 "HPM, HIV Positive Men",
                                 "HPW, HIV Positive Women",
                                 "BSSD, Between-subject Standard Deviation",
                                 "WSSD, Within-subject Standard Deviation"),
            rowlabel = "Population strata",
            ctable = TRUE)

```


```{r bw_model_setup, include = FALSE, warning = FALSE, message = FALSE}

# These are the people who reported more than one partner
# However, even though they may have reported more than one partner,
# they may not have reported ages for all partners and thus, they may
# have a missing age differences (and thus "-Inf" for bw)

cc <- partdfimp %>%
  filter(.imp == 0, relcount > 1, bridgewidth != -Inf) %>%
  group_by(sex) 

# Among those with more than 1 partner
bwsum <- cc %>%
  summarise(n = n(),
            Median = median(bridgewidth),
            Mean = mean(bridgewidth),
            sd = sd(bridgewidth),
            lwr = summary(bridgewidth)[[2]],
            upr = summary(bridgewidth)[[5]])


# Does HIV predict bridgewidths (neg bin models)?
# Does HIV predict whether a participant had a concurrent rel in past year (logistic models)?

tidysum <- cc %>% 
  nest() %>%
  mutate(modelbw = map(data, bwmodel),
         modelsumbw = map(modelbw, tidygam), # Create tidy summary of each model and store as modelsum var in nested df
         predsbwage = map(modelbw, gampredsage)) # Create predictions across dif vals of age (our spline var))

# Unnest the tidy summary, to see the tidy model estimates for each model
bwmodcoef <- tidysum %>%
  unnest(modelsumbw, .drop = TRUE) 

# Unnest the tidy summary, to see the tidy model predictions for values of age
# for each model
bwmodpredage <- tidysum %>%
  unnest(predsbwage, .drop = TRUE)

```

```{r bw_model_tab_setup, include = FALSE}

# These are the pooled coefficients from mice main analysis
# BE CAREFUL TO UPDATE THESE NUMBERS IF "CTSBS_AGE_MIXING.RMD" CHANGES
mpoolEBWR <- 1.93
mpoolEBWRlwr <- 0.69
mpoolEBWRupr <- 5.41
wpoolEBWR <- 2.76
wpoolEBWRlwr <- 1.16
wpoolEBWRupr <- 6.59

# These are the coefficients from the complete case analysis
mccEBWR <- round(bwmodcoef$ratio[13], 2)
mccEBWRlwr <- round(bwmodcoef$rlwr[13], 2)
mccEBWRupr <- round(bwmodcoef$rupr[13], 2)
wccEBWR <- round(bwmodcoef$ratio[2], 2)
wccEBWRlwr <- round(bwmodcoef$rlwr[2], 2)
wccEBWRupr <- round(bwmodcoef$rupr[2], 2)

mx <- matrix(ncol = 2, nrow = 2)
colnames(mx) <- c("Men EBWR (95% CI)", "Women EBWR (95% CI)")
rownames(mx) <- c("CC", "MI")

mx[1, 1] <- paste0(mccEBWR, " (", mccEBWRlwr, " — ", mccEBWRupr, ")")
mx[1, 2] <- paste0(wccEBWR, " (", wccEBWRlwr, " — ", wccEBWRupr, ")")
mx[2, 1] <- paste0(mpoolEBWR, " (", mpoolEBWRlwr, " — ", mpoolEBWRupr, ")")
mx[2, 2] <- paste0(wpoolEBWR, " (", wpoolEBWRlwr, " — ", wpoolEBWRupr, ")")

```

<br>
<br>

```{r bw_model_tab, echo = FALSE, fig.width = 10}


mx %>%
  htmlTable(caption = "<b>Table 3. Model coefficients for relationship between HIV and bridge width. The Expected Bridge Width Ratio (EBWR) is the ratio of expected bridge widths for those who are HIV positive compared to those who are HIV negative. The EBWR is derived from the negative binomial model that also adjusts for the age of the participant.</b>",
            tfoot = txtMergeLines("The complete case (CC) analysis uses the raw dataset and observations for which there were no missing data on variables used in the analysis (Women: n = 56; Men: n = 58). The multiple imputation (MI) analysis  pools coefficients according to Rubin's Rules from the combined 100 imputed datasets presented in the main text."),
            rowlabel = "Analysis type",
            ctable = TRUE)

```


```{r prop_relcount_strata, include = FALSE}
strata <- smalldf %>%
  distinct(id, .keep_all = T) %>%
  select(id, sex, hiv, relcount) %>%
  mutate(mp = ifelse(relcount > 1, "mp", "one only")) %>%
  na.omit()

strata

strata %>%
  group_by(sex, hiv, mp) %>%
  summarise(n = n()) %>%
  mutate(prop = (n / sum(n)) * 100)

```

